linkWorkspacePackages: true

packages:
  - 'packages/@repo/*'
  - 'packages/@sanity/cli'
  - 'packages/@sanity/cli-build'
  - 'packages/@sanity/cli-core'
  - 'packages/@sanity/cli-e2e'
  - 'packages/@sanity/cli-test'
  - 'packages/@sanity/eslint-config-cli'
  - 'packages/create-sanity'
  - 'fixtures/*'
  - 'tmp/*'

catalog:
  # Linting
  eslint: ^10.2.1
  '@eslint/compat': ^2.0.5
  publint: ^0.3.18

  # GROQ
  groq-js: ^1.30.1

  # Sanity
  sanity: ^5.23.0
  '@sanity/vision': ^5.23.0
  '@sanity/types': ^5.23.0
  '@sanity/schema': ^5.23.0
  '@sanity/client': ^7.22.0
  '@sanity/codegen': ^6.0.3
  '@sanity/telemetry': ^0.9.0

  # Build & Development Tools
  typescript: ^5.9.3
  vite: ^7.3.2
  tsx: ^4.21.0
  '@vitejs/plugin-react': ^5.2.0

  # Testing
  vitest: ^4.1.5
  '@vitest/coverage-istanbul': ^4.1.5
  nock: ^14.0.14
  node-pty: ^1.1.0
  dotenv: ^17.3.1
  strip-ansi: ^7.1.0

  # CLI Framework
  '@oclif/core': ^4.10.6
  '@oclif/plugin-help': ^6.2.45
  '@oclif/plugin-not-found': ^3.2.81

  # Utilities
  debug: ^4.4.3
  jsdom: ^29.0.2
  zod: ^4.3.6
  'get-tsconfig': ^4.14.0
  'import-meta-resolve': ^4.2.0
  execa: ^9.6.0
  read-package-up: ^12.0.0
  ora: ^9.0.0
  rxjs: ^7.8.2
  tinyglobby: ^0.2.16
  lodash-es: ^4.18.1
  '@types/lodash-es': ^4.17.12
  yaml: ^2.8.4

  # Build Tools
  '@swc/core': ^1.15.33
  '@swc/cli': ^0.8.1
  rimraf: ^6.0.1
  '@sanity/pkg-utils': ^10.4.18
  oxfmt: ^0.45.0

  # Type Definitions
  '@types/node': ^20.19.39
  '@types/debug': ^4.1.13
  '@types/jsdom': ^28.0.1

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - 'groq-js'
  - 'groq'
  - 'lodash-es'
  - 'react-rx'
  - 'sanity'
  - 'use-effect-event'
  - 'dotenv'
  - 'oxfmt'
  - '@oxfmt/*'
  # Bump for jiti with ts path support, can remove after ~May 9th
  - 'jiti@2.7.0'
